<a href="https://colab.research.google.com/github/0ArchLinux0/Temp/blob/main/DS_Class.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/assets/train.csv")
data

id  gender   age  hypertension  heart_disease ever_married  \
0     49459    Male   9.0             0              0           No   
1     69461  Female  49.0             0              0          Yes   
2     29258  Female  37.0             0              0           No   
3     47811  Female  72.0             0              0          Yes   
4      5353    Male  52.0             0              1           No   
...     ...     ...   ...           ...            ...          ...   
3572  46093  Female  28.0             0              0          Yes   
3573  11882    Male  34.0             0              0           No   
3574  44179  Female  41.0             0              0          Yes   
3575  45048  Female  21.0             0              0           No   
3576  15241  Female  63.0             1              1           No   

          work_type Residence_type  avg_glucose_level   bmi smoking_status  \
0          children          Rural              61.75  16.2        Unknown   
1          Govt_job          Urban              90.58  23.2        Unknown   
2           Private          Urban              89.11  24.1   never smoked   
3     Self-employed          Urban             239.82  35.8   never smoked   
4           Private          Rural             101.50  31.2         smokes   
...             ...            ...                ...   ...            ...   
3572        Private          Rural              56.47  22.7   never smoked   
3573        Private          Urban              94.15  28.6   never smoked   
3574        Private          Urban              80.77  21.1   never smoked   
3575        Private          Urban             134.45  29.1   never smoked   
3576       Govt_job          Urban             174.43  24.3   never smoked   

      stroke  
0          0  
1          0  
2          0  
3          0  
4          0  
...      ...  
3572       0  
3573       0  
3574       0  
3575       0  
3576       0  

[3577 rows x 12 columns]

In [ ]:
from sklearn import svm
from sklearn.preprocessing import StandardScaler

# Linear model is not predicting properly
# So we have to use rbf kernel which is the code below
svm_clf = svm.SVC(kernel = 'linear', C=0.5, gamma=0.5)
y = data.iloc[:, [-1]]
print('sum', y.sum())
# label
x = data.drop(["id", "stroke"], axis = 1)
x.gender = x.gender.replace({'Male':0, 'Female':1, 'Other':2})
x.work_type = x.work_type.replace({'children':0, 'Govt_job':1, 'Private':2, 'Self-employed':3, 'Never_worked': 4})
x.Residence_type = x.Residence_type.replace({'Rural':0, 'Urban':1})
x.smoking_status = x.smoking_status.replace({'never smoked':0, 'Unknown':1, 'formerly smoked':2, 'smokes':3})
x.ever_married = x.ever_married.replace({'Yes':1, 'No':0})
x = x.fillna(0)
print(x)

scaler = StandardScaler()
scaler.fit(x)
x_scaled = scaler.transform(x)
# print(x_scaled)
print('yyyyyyy')
Y = np.ravel(y);
print('y sum', y.sum())
print(Y) 
svm_clf.fit(x_scaled, np.ravel(y))

sum stroke    179
dtype: int64
      gender   age  hypertension  heart_disease  ever_married  work_type  \
0          0   9.0             0              0             0          0   
1          1  49.0             0              0             1          1   
2          1  37.0             0              0             0          2   
3          1  72.0             0              0             1          3   
4          0  52.0             0              1             0          2   
...      ...   ...           ...            ...           ...        ...   
3572       1  28.0             0              0             1          2   
3573       0  34.0             0              0             0          2   
3574       1  41.0             0              0             1          2   
3575       1  21.0             0              0             0          2   
3576       1  63.0             1              1             0          1   

      Residence_type  avg_glucose_level   bmi  smoking_s

SVC(C=0.5, gamma=0.5, kernel='linear')

In [ ]:
from sklearn import svm
from sklearn.preprocessing import StandardScaler

# RBF kernel is a suitable model for this classification problem
svm_clf = svm.SVC(kernel = 'rbf', C=4, gamma=0.5)
y = data.iloc[:, [-1]]
print('sum', y.sum())
# label
x = data.drop(["id", "stroke"], axis = 1)
x.gender = x.gender.replace({'Male':0, 'Female':1, 'Other':2})
x.work_type = x.work_type.replace({'children':0, 'Govt_job':1, 'Private':2, 'Self-employed':3, 'Never_worked': 4})
x.Residence_type = x.Residence_type.replace({'Rural':0, 'Urban':1})
x.smoking_status = x.smoking_status.replace({'never smoked':0, 'Unknown':1, 'formerly smoked':2, 'smokes':3})
x.ever_married = x.ever_married.replace({'Yes':1, 'No':0})
x = x.fillna(0)
# print(x)

scaler = StandardScaler()
scaler.fit(x)
x_scaled = scaler.transform(x)

svm_clf.fit(x_scaled, np.ravel(y))

# test_data = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/assets/test.csv")
# test_x = test_data.drop(["id"], axis = 1)
# test_x.gender = test_x.gender.replace({'Male':0, 'Female':1, 'Other':2})
# test_x.work_type = test_x.work_type.replace({'children':0, 'Govt_job':1, 'Private':2, 'Self-employed':3, 'Never_worked': 4})
# test_x.Residence_type = test_x.Residence_type.replace({'Rural':0, 'Urban':1})
# test_x.smoking_status = test_x.smoking_status.replace({'never smoked':0, 'Unknown':1, 'formerly smoked':2, 'smokes':3})
# test_x.ever_married = test_x.ever_married.replace({'Yes':1, 'No':0})
# test_x = test_x.fillna(0)

# scaler = StandardScaler()
# scaler.fit(test_x)
# test_x_scaled = scaler.transform(test_x)
# # print(test_x_scaled)
# print(test_x_scaled)

# prediction = svm_clf.predict(test_x_scaled)
# print(prediction)
# print(prediction.sum())
# # print(np.where(prediction == 1))
# indices = np.where(prediction == 1)
# print(test_x[prediction == 1].smoking_status)

sum stroke    179
dtype: int64


SVC(C=4, gamma=0.5)

In [ ]:
test_data = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/assets/test.csv")
test_x = test_data.drop(["id"], axis = 1)
test_x.gender = test_x.gender.replace({'Male':0, 'Female':1, 'Other':2})
test_x.work_type = test_x.work_type.replace({'children':0, 'Govt_job':1, 'Private':2, 'Self-employed':3, 'Never_worked': 4})
test_x.Residence_type = test_x.Residence_type.replace({'Rural':0, 'Urban':1})
test_x.smoking_status = test_x.smoking_status.replace({'never smoked':0, 'Unknown':1, 'formerly smoked':2, 'smokes':3})
test_x.ever_married = test_x.ever_married.replace({'Yes':1, 'No':0})
test_x = test_x.fillna(0)

scaler.fit(test_x)
test_x_scaled = scaler.transform(test_x)

prediction = svm_clf.predict(test_x_scaled)
print(prediction.sum())
indices = np.where(prediction == 1)
print(indices)
print(test_x[prediction == 1])

22
(array([  16,  105,  134,  368,  383,  463,  474,  480,  513,  666,  700,
       1014, 1018, 1031, 1033, 1074, 1174, 1232, 1237, 1280, 1507, 1525]),)
      gender   age  hypertension  heart_disease  ever_married  work_type  \
16         0  34.0             0              0             1          2   
105        1  49.0             0              0             1          2   
134        0  76.0             0              0             1          2   
368        0  51.0             0              0             1          2   
383        0  60.0             0              0             1          3   
463        0  79.0             0              0             1          3   
474        0  75.0             0              0             1          1   
480        0  30.0             0              0             1          2   
513        1  76.0             0              0             1          2   
666        0  31.0             0              0             1          2   
700        

In [ ]:
# with open("/content/drive/MyDrive/Colab Notebooks/assets/y_pred_example.txt", "w") as ofs:
#   ofs.write()
prediction = np.asarray(prediction, dtype = int)
print(prediction)
np.savetxt("/content/drive/MyDrive/Colab Notebooks/assets/y_pred_example.txt",prediction, fmt='%i')
ck_file = np.loadtxt("/content/drive/MyDrive/Colab Notebooks/assets/y_pred_example.txt")
ck_file


[0 0 0 ... 0 0 0]


array([0., 0., 0., ..., 0., 0., 0.])